//
//  CommonImg.h
//  CAMELLIAE
//
//  Created by 张越 on 16/3/17.
//  Copyright © 2016年 张越. All rights reserved.
//

#ifndef CommonImg_h
#define CommonImg_h


#define FindImg                       @"find.png"
#define DisFindImg                    @"find-dis.png"
#define UserImg                       @"user.png"
#define DisUserImg                    @"user-dis.png"
#define VIPImg                        @"VIP.png"
#define DisVIPImg                     @"VIP-dis.png"
#define ServeImg                      @"serve.png"
#define DisServeImg                   @"serve-dis.png"
#define ActivityImg                   @"activity.png"
#define DisActivityImg                @"activity-dis.png"
#define StoreImg                      @"store.png"
#define DisStoreImg                   @"store-dis.png"
#define LoginVCCode                   @"icon_code.png"
#define LoginVCSee                    @"icon_codeSee.png"
#define LoginVCUnSee                  @"icon_codeUnSee.png"
#define LoginVCQQ                     @"QQ.png"
#define LoginVCSina                   @"sina weibo.png"
#define LoginVCUser                   @"icon_user.png"
#define LoginVCWechat                 @"wechat.png"
#define LoginVCHightLightWechat       @"第三方_微信_点击.png"
#define LoginVCLogo                   @"登录注册－logo.png"
#define LoginVCDefaultImg             @"userHeaderImg.png"
//#define NavcBackBtnImg                @"icon_back.png"
#define NavcBackBtnImg                @"返回_黑色.png"
#define BackBtnImg                    @"backIcon.png"
#define InformationImg                @"information.png"
#define ActivityImg                   @"activity.png"
#define ServeImg                      @"serve.png"
#define ImagesImg                     @"images.png"
#define Images1Img                    @"图库.png"
#define ShareBtnImg                   @"new详情_分享.png"
#define CommentImg                    @"new详情_评论.png"
#define DisFavedImg                   @"new详情_未收藏.png"
#define DisLikeImg                    @"dis-like.png"
#define FavedImg                      @"new详情_收藏.png"
#define LikeImg                       @"like.png"
#define CloseImg                      @"close.png"
#define DefaultLikeImg                @"like copy.png"
#define DouBanShareImg                @"豆瓣.png"
#define EmailShareImg                 @"复制链接.png"
#define QQShareImg                    @"ShareQQ.png"
#define SinaShareImg                  @"微博.png"
#define Wechat_CShareImg              @"微信.png"
#define wechat_momentShareImg         @"朋友圈.png"
#define DownLoadImg                   @"goldLoad.png"
#define ImageCloseBtnImg              @"goldClose.png"
#define LeadOnePageImg                @"leadOnePage1.png"
#define LeadTwoPageImg                @"leadTwoPage2.png"
#define LeadThreePageImg              @"leadThreePage3.png"
#define LeadFourPageImg               @"leadFourPage4.png"
#define LeadBtnImg                    @"launchImageBtn.png"
#define NewLogoImg                    @"logo-文字.png"
#define LeadBottomPageImg             @"Group Copy.png"
#define ActivitySymbolImg             @"new活动icon.png"
#define InformationModuleImg          @"new资讯icon.png"
#define ActivityCurrentCityImg        @"Combined Shape.png"
#define ServeModuleImg                @"new生活icon.png"
#define VideoPlayImg                  @"videoPlay.png"
#define EnterOtherListImg             @"enterList.png"
#define AttentionedImg                @"attentioned.png"
#define CloseAppointmentImg           @"closeAppointment.png"
#define AboutMesEnterImg              @"AboutMesEnter.png"
#define HotLifeEnterImg               @"HotLifeEnter.png"
#define DecorateImg                   @"decorate.png"
#define HotTopicEnterImg              @"HotTopicEnter.png"
#define WXPayImg                      @"WXPay.png"
#define ZFBPayImg                     @"ZFBPay.png"
#define LaunchImg                     @"currentLaunchImg6.png"
#define LaunchImg5                    @"currentLaunchImg5.png"
#define LaunchImg6                    @"currentLaunchImg6.png"
#define LaunchImg6p                   @"currentLaunchImg6p.png"
#define PersonalCenterBgImg           @"newPersonalBgImage.png"
#define VIPHeartTimeImg               @"timeBgView.png"
#define VIPNOMesImg                   @"NoVIPMes.png"
#define NOCommentImg                  @"无评论.png"
#define SpecialTopicAddressImg        @"specialAddressIcon.png"
#define MesCodeImg                    @"注册－验证码.png"
#define FormulateImg                  @"定制旅游.png"
#define ClearTextBtnImg               @"clearText.png"
#define LoaingColorImg                @"加载色块1.png"
#define NavBarShareImg                @"navBarShare.png"
#define NetErrorImg                   @"newNetError.png"
#define SmallVideoPlayerImg           @"smallVideoPlayer.png"
#define ImageNamePromptImg            @"相册名指示.png"
#define Like_imageImg                 @"like_image.png"
#define DisLike_imageImg              @"disLike_image.png"
#define PerfectInfoNickNameImg        @"nickName.png"
#define PerfectInfoInviteCodeImg      @"inviteCode.png"
#define MainInterfaceCalendarImg      @"主页面活动日历.png"
#define MainInterfaceInformationImg   @"主页面资讯.png"
#define MainInterfacePhotoImg         @"主页面图集.png"
#define MainInterfaceTopicImg         @"主页面专题.png"
#define MainInterfaceActivityPromptImg  @"提醒喇叭.png"
#define MainInterfaceGoodsImg           @"主页面单品.png"
#define MainInterfaceMoreMesImg         @"主页查看更多.png"
#define MainInterfaceModuleActivityPromptImg @"首页活动提示.png"
#define VIPNAVCBgImg                    @"会员主页_导航栏背景.png"
#define VIPTopBgBgImg                   @"会员主页_背景.png"
#define VIPTimeLineDirectionImg         @"大事记_指向.png"
#define VIPBackImg                      @"会员主页_返回.png"
#define VIPShareImg                     @"会员主页_分享.png"
#define VIPBlackBackImg                 @"会员主页_黑_返回.png"
#define VIPBlackShareImg                @"会员主页_黑_分享.png"
#define VIPDetailTimeLineWriteImg       @"会员主页_写大事记.png"
#define Activity_serveClassImg          @"活动_高端定制_课程头图.png"
#define Activity_serveTravelImg         @"活动_高端定制_旅游头图.png"
#define MoreMessageImg                  @"首页_查看更多.png"
#define NewTopicBackImg                 @"专题推荐、精彩选集_返回.png"
#define NewTopicShareImg                @"专题推荐、精彩选集_分享.png"
#define NewScreenCloseImg               @"活动_筛选_收起.png"
#define NewScreenOpenImg                @"活动_筛选_展开.png"
#define DetailMessageBackImg            @"导航栏_返回.png"
#define DetailMessageCollectImg         @"详情_收藏.png"
#define DetailMessageCollectedImg       @"详情_收藏成功.png"
#define DetailMessageShareImg           @"详情_分享.png"
#define DetailMessageTimeImg            @"详情_时间.png"
#define DetailMessageTeleImg            @"详情_电话.png"
#define DetailMessageLvlImg             @"详情_等级.png"
#define DetailMessageAddressImg         @"详情_地点.png"
#define DetailMessageSponsorImg         @"详情_主办方.png"
#define DetailMessageEnterMapImg        @"详情_信息点跳转.png"
#define MainInfaceSearchImg             @"首页_搜索.png"
#define CalendarLeftBtnImg              @"calendar_unfold_arrow_left.png"
#define CalendarRightBtnImg             @"calendar_unfold_arrow_right.png"
#define ActivitySubscribeImg            @"already booked label.png"
#define RecommendNumberEnterImg         @"专题推荐_数目展示.png"
#define DeleteOldSearchImg              @"删除.png"

#define PersonalCenterSysMesImg           @"系统消息.png"
#define PersonalCenterSettingImg          @"设置.png"
#define PersonalCenterCodeScanImg         @"扫一扫.png"
#define PersonalCenterMessageStateImg     @"消息_状态.png"
#define PersonalCenterMessageImg          @"消息.png"
#define PersonalCenterPointsImg           @"我的积分.png"
#define PersonalCenterUserHomeImg         @"我的名片.png"
#define PersonalCenterUserInfoImg         @"我的资料.png"
#define PersonalCenterUserOrderImg        @"我的订单.png"
#define PersonalCenterUserAppointmentImg  @"我的预订.png"
#define PersonalCenterUsercollectImg      @"我的收藏.png"
#define PersonalCenterDiscountCouponImg   @"我的卡券.png"
#define PersonalCenterUserMessageImg      @"我的私信.png"
#define PersonalCenterUserPointsImg       @"我的会员.png"

#define PersonalNewWalletImg              @"钱包中心_钱包.png"
#define PersonalNewSignImg                @"钱包中心_签到领积分.png"
#define PersonalNewRecommendImg           @"钱包中心_推荐卡枚连.png"
#define PersonalGetCouponsImg             @"领劵中心_icon.png"
#define PresonalNewOpinionImg             @"意见反馈.png"
#define PersonalMesEditImg                @"编辑.png"
#define PersonalAdvertisementImg          @"广告.png"
#define PersonalAdvertisement1Img         @"广告位02.png"
#define PersonalAdPinkGoldCardImg         @"粉金卡邀请.png"

#define PersonalCenterUserEnterVCImg      @"my_icon_enter.png"
#define NewPersonalCenterUserEnterVCImg   @"进入.png"
#define PersonalCenterUserBrowsedImg      @"首页-浏览.png"
#define PersonalCenterUserCollectedImg    @"首页-收藏.png"
#define PresonalCenterUserDisbrowsedImg   @"首页-未浏览.png"
#define PersonalCenterUserDisCollectedImg @"首页-未收藏.png"
#define PersonalCenterUserLikeImg         @"首页-点赞.png"
#define PersonalCenterUserDisLikeImg      @"首页-未点赞.png"
#define PersonalCenterUserOpenUpImg       @"一级类目选择下拉.png"
#define PersonalCenterUserPackingUpImg    @"packingUp.png"
#define PersonalCenterNoMesImg            @"无消息.png"
#define PersonalCenterNoCollectionImg     @"无收藏.png"
#define PersonalCenterNoAppointmentImg    @"无预约.png"
#define PersonalCenterNoOrderImg          @"无订单.png"
#define PersonalCenterNoCouponsImg        @"no_coupons.png"

#define PersonalMemberlevelImg            @"VIPLevel.png"
#define PersonalMemberPointsImg           @"VIPPoints.png"
#define RecommendImg                      @"iOS-58.png"
#define ColorImg                          @"eeeeee.png"
#define SearchBarImg                      @"搜索示意.png"
#define WriteMessageImg                   @"写大事记.png"
#define WriteExpressImagebtnImg           @"大事记_添加照片.png"
#define ImageDeleteImg                    @"发布大事记_图片删除.png"
#define DeleteTimeLineImg                 @"大事记_删除.png"
#define ActivityBgCommentAndRecordImg     @"活动提示背景.png"
#define NewDetailCloseImg                 @"newDetailClose.png"
#define NewShareImg                       @"newShare.png"
#define LaunchBannerImg                   @"登录注册_头图_1.png"
#define PersonalCardEditImg               @"我的名片_编辑.png"
#define BothFollowImg                     @"我的关注_互相关注.png"
#define ScreenEnterImg                    @"活动首页_筛选_跳转页面.png"
#define NOCalendarActivityImg             @"calendar_activity_no.png"
#define SelectTypeWhiteImg                @"activity_mixture_charge_choice.png"
#define AlterViewCloseBtnImg              @"alterViewCloseBtn.png"
#define NewPayTypeZFBImg                  @"pay_alipay.png"
#define NewPayTypeWXImg                   @"pay_wechat.png"
#define PayTypeEnterImg                   @"pay_arrow.png"
#define UpGradeBgImg                      @"背景.png"
#define UpGradeMessageShowBgLongImg       @"会员特权_弹窗背景.png"
#define UpGradeTopTitleImg                @"会员标题.png"
#define UpGradePinkImg                    @"升级粉色.png"
#define UpGradeBlackPigmentImg            @"升级黛色.png"
#define UpGradeGoldImg                    @"升级金色.png"
#define UpGradeGrayImg                    @"升级墨色.png"
#define UpGradeBuyPinkSilverSuccessImg    @"粉银购买成功_弹窗.png"
#define UpGradeBuyPinkGoldSuccessImg      @"粉金购买成功_弹窗.png"
#define UpGradeBuyPigmentSuccessImg       @"购买成功返回-黛色.png"
#define UpGradeBuyGoldSuccessImg          @"购买成功返回-金色.png"
#define UpGradeMessageShowBgImg           @"特权背景.png"
#define UpGradeMessageTopPigmentImg       @"黛色_皇冠.png"
#define UpGradeMessageTopGoldImg          @"金色_皇冠.png"
#define UpGradeMessageTopGrayImg          @"墨色_皇冠.png"
#define UpGradeMessageTopPinkImg          @"皇冠_粉色.png"
#define UpGradeMessageTagBgImg            @"Polygon Copy 2.png"
#define UpGradeVIPPriceImg                @"人民币.png"
#define UpGradeVIPWXPayTypeImg            @"VIP微信.png"
#define UpGradeVIPZFBPayTypeImg           @"VIP支付宝.png"
#define UpGradeVIPRealPayTypeImg          @"VIP线下支付.png"
#define OwnVIPBgImg                       @"我的会员_深色底.png"
#define OwnVIPGradeImg                    @"VIP等级 icon.png"
#define OwnVIPPointsImg                   @"VIP积分icon.png"
#define OwnVIPUpImg                       @"VIP特权 icon.png"
#define OwnVIPPigmentBgImg                @"我的会员_黛色会员.png"
#define OwnVIPPinkBgImg                   @"我的会员_粉色会员.png"
#define OwnVIPGoldBgImg                   @"我的会员_金色会员.png"
#define OwnVIPDarkBgImg                   @"我的会员_墨色会员.png"
#define CMLNewPersonalLvl1                @"我的卡片-粉色会员 展开效果.png"
#define CMLNewPersonalLvl2                @"我的卡片-黛色会员 展开效果.png"
#define CMLNewPersonalLvl3                @"我的_卡片-金色 展开.png"
#define CMLNewPersonalLvl4                @"我的_卡片-墨色 展开.png"
#define CMLVIPCenterBgImg                 @"会员中心 -卡片-bg.png"
#define CMLVIPCenterBg2Img                @"会员中心 -卡片-bg2.png"
#define CMLUpGradeImg                     @"升级会员.png"
#define CMLUserViewBackImg                @"我的页面返回.png"
#define UpGradeTitleImg                   @"名字.png"
#define UserVerbImg                       @"签到.png"
#define UserUpGradePromImg                @"会员中心-三角.png"
#define UserUpGradeBg1Img                 @"背景1 copy.png"

/*4.2.0*/
/*个人中心-会员身份卡片z-展开*/
#define CMLNewPersonalLvl1Card            @"我的_卡片-粉色.png"
#define CMLNewPersonalLvl11Card           @"我的_卡片-紫色.png"/*粉银*/
#define CMLNewPersonalLvl12Card           @"我的_卡片-粉金.png"
#define CMLNewPersonalLvl13Card           @"我的_卡片-粉钻.png"
#define CMLNewPersonalLvl2Card            @"我的_卡片-黛色.png"
#define CMLNewPersonalLvl11PartnerCard    @"我的_卡片-城市合伙人.png"
/*个人中心图标*/
#define CMLNewPersonalLvl1Icon            @"个人中心_粉色_v.png"
#define CMLNewPersonalLvl11Icon           @"个人中心_紫色_v.png"/*粉银图标v*/
#define CMLNewPersonalLvl12Icon           @"个人中心_粉金_v.png"
#define CMLNewPersonalLvl13Icon           @"个人中心_粉钻_v.png"
#define CMLNewPersonalLvl2Icon            @"个人中心_黛色_v.png"
#define CMLNewPersonalLvl11PartnerIcon    @"个人中心_城市合伙人_v.png"

#define CMLNewPersonalMemberEnterIcon     @"member_enter.png"
#define CMLNewPersonalMemberEnterBgImg    @"member_enter_bg.png"
#define CMLNewPersonalMemberEnterButton   @"按钮.png"
#define CMLPersonalUpgradeConfirmButton   @"粉金升级提示_确定按钮.png"
#define CMLPersonalUpgradeSucceedButton   @"粉金升级提示_成功按钮.png"

/*会员中心-图标*/
#define CMLMemberCenterLvl1Icon           @"会员中心_粉色_v.png"
#define CMLMemberCenterLvl11Icon          @"会员中心_粉银_v.png"/*会员中心粉银图标v*/
#define CMLMemberCenterLvl12Icon          @"会员中心_粉金_v.png"
#define CMLMemberCenterLvl13Icon          @"会员中心_粉钻_v.png"
#define CMLMemberCenterLvl2Icon           @"会员中心_黛色_v.png"
#define CMLMemberCenterLvl11PartnerIcon   @"会员中心_合伙人_v.png"
#define CMLMemberCenterLvlNoSelectIcon    @"会员中心_未选状态_v.png"
/*会员中心-背景-select*/
#define CMLMemberCenterLvl1SelectBgImg    @"会员中心_粉色.png"
#define CMLMemberCenterLvl11SelectBgImg   @"会员中心_粉银.png"
#define CMLMemberCenterLvl12SelectBgImg   @"会员中心_粉金.png"
#define CMLMemberCenterLvl13SelectBgImg   @"会员中心_粉钻.png"
#define CMLMemberCenterLvl2SelectBgImg    @"会员中心_黛色.png"
#define CMLMemberCenterLvl11PartnerSelect @"会员中心_城市合伙人_bg.png"
#define CMLMemberCenterLvlNoSelectBgImg   @"会员中心_未选状态.png"

/*钱包中心-icon*/
#define CMLWalletCenterLvl1Icon           @"钱包中心_黛色_粉色.png"
#define CMLWalletCenterLvl2Icon           @"钱包中心_黛色_紫色.png"
/*钱包中心-背景卡片*/
#define CMLWalletCenterLvl1BgImage        @"钱包中心_粉色.png"
#define CMLWalletCenterLvl2BgImage        @"钱包中心_紫色.png"
/*4.2.0*/

/*会员中心*/
#define CMLNewUpGradeBlackPigment1Img     @"黛色会员_魅力女神卡.png"
#define CMLNewUpGradeBlackPigment2Img     @"黛色会员_企业精英卡.png"
#define CMLNewBlackPigmentNoSelect1Img    @"未选状态_魅力女神卡.png"
#define CMLNewBlackPigmentNoSelect2Img    @"未选状态_企业精英卡.png"
#define CMLNewUpGradeBlackPigmentImg      @"会员中心_黛色.png"
#define CMLNewUpGradePinkImg              @"会员中心_黛色_粉色.png"
#define CMLNewUpGradeGoldImg              @"会员中心-金色会员.png"
#define CMLNewUpGradeGrayImg              @"会员中心-墨色会员.png"
#define CMLNewBlackPigmentNoSelectImg     @"会员中心_黛色_未选中.png"
#define CMLNewGoldNoSelectImg             @"会员中心-金色会员未选中状态.png"
#define CMLNewPinkNoSelectImg             @"会员中心_黛色_粉色_未选中.png"
#define CMLNewUpGradeBtnImg               @"立即升级会员.png"
#define CMLNewUpGradeRenewBtnImg          @"立即续费.png"
#define CMLNewUpGradeFinalPaymentBtnImg   @"支付尾款.png"
#define CMLVIPCard1Img                    @"魅力女神卡.png"
#define CMLVIPCard2Img                    @"企业认证.png"
#define CMLVIPInviteImg                   @"会员联盟专享.png"
#define CMLNewNoSelectImg                 @"new未选状态.png"
#define CMLNewSelectImg                   @"new选中状态.png"
/*黛色分享*/
#define CMLMemberInvitationBgImage           @"黛色_分享页__黛色.png"
#define CMLMemberInvitationPinkGoldBgImage   @"黛色_分享页_分享粉金.png"
#define CMLMemberInvitationShareImage        @"落地页_分享.png"
#define CMLMemberInvitationPinkBannerImage   @"粉金邀请详情banner.png"

/*黛色会员权益图标*/
#define CMLEquityTitleSelectImg           @"会员专属权益.png"
#define CMLEquityTitleNoSelectImg         @"会员专属权益_灰色.png"
#define CMLCustomGiftSelectImg            @"定制入会礼.png"
#define CMLCustomGiftNoSelectImg          @"定制入会礼_灰色.png"
#define CMLShareMallSelectImg             @"共享商城系统.png"
#define CMLShareMallNoSelectImg           @"共享商城系统_灰色.png"
#define CMLDiscountCardSelectImg          @"品牌折扣卡.png"
#define CMLDiscountCardNoSelectImg        @"品牌折扣卡_灰色.png"
#define CMLFashionSalonSelectImg          @"时尚沙龙.png"
#define CMLFashionSalonNoSelectImg        @"时尚沙龙_灰色.png"
#define CMLVIPHousekeeperSelectImg        @"VIP管家预约.png"
#define CMLVIPHousekeeperNoSelectImg      @"VIP管家预约_灰色.png"

/*黛色协议*/
#define CMLCheckButtonNoSelectImg         @"会员中心_黛色会员协议_未勾选.png"
#define CMLCheckButtonSelectImg           @"会员中心_黛色会员协议_勾选.png"
#define CMLConfirmButtonNoSelectImg       @"会员中心_黛色会员_确定_为选中.png"
#define CMLConfirmButtonSelectImg         @"会员中心_黛色会员_确定_选中.png"
/*钱包中心*/
#define CMLWalletCenterTopBackgroundImage             @"钱包中心_背景.png"
#define CMLWalletCenterEarningsImage                  @"钱包中心_我的收益_卡片.png"
#define CMLWalletCenterEarningsDarkBgImage            @"钱包中心_紫色.png"
#define CMLWalletCenterEarningsPinkBgImage            @"钱包中心_粉色.png"
#define CMLWalletCenterEarningsIconImage              @"钱包中心_收益_icon.png"
#define CMLWalletCenterEarningsLogoImage              @"钱包中心_logo.png"
#define CMLWalletCenterWithdrawalBtnImage             @"选中_申请提现.png"
#define CMLWalletCenterWithdrawalBtnNoSelectedImage   @"未选中_申请提现.png"
#define CMLWalletCenterWhiteBackBtnImage              @"返回_白色.png"
#define CMLWalletCenterBlackBackBtnImage              @"返回_黑色.png"
#define CMLWalletCenterABImage                        @"钱包中心_ A B级.png"
#define CMLWalletCenterTeamDetailImage                @"钱包中心_团队详情_返回.png"
#define CMLWalletCenterMYTEAMImage                    @"MY TEAM.png"
#define CMLWalletCenterProbationImage                 @"钱包中心_试用会员.png"
#define CMLWalletCenterTriangleImage                  @"钱包中心_三角形.png"

/*权益详情页*/
//#define CMLMemberEquityTopBgImage                     @"钱包中心_我的收益_卡片.png"
#define CMLMemberEquityContentImage                   @"会员中心_权益内容_icon.png"
#define CMLMemberEquityIntroImage                     @"会员中心_权益说明02_icon.png"
#define CMLMemberEquitySalonIntroImage                @"会员中心_权益说明_icon.png"
#define CMLMemberEquityAppointmentImage               @"会员中心_预约服务_icon.png"
#define CMLMemberEquityDelleteImage                   @"会员中心_删除.png"
#define CMLMemberEquityNotUseImage                    @"会员中心_未使用.png"
#define CMLMemberEquityBeenUseImage                   @"会员中心_已使用.png"
#define CMLMemberEquityBeenCheckImage                 @"会员中心_选择服务_勾选.png"
#define CMLMemberEquityNotCheckImage                  @"会员中心_选择服务_未勾选.png"
#define CMLMemberEquityOneImage                       @"会员中心_1.png"
#define CMLMemberEquityTwoImage                       @"会员中心_2.png"
#define CMLMemberEquitythreeImage                     @"会员中心_3.png"

#define CMLMemberEquityExclusiveImage                 @"会员权益_超值专享.png"
#define CMLMemberEquityShareMallImage                 @"会员权益_共享商城系统.png"
#define CMLMemberEquityDiscountCardImage              @"会员权益_品牌折扣卡.png"
#define CMLMemberEquitySalonImage                     @"会员权益_时尚沙龙.png"
#define CMLMemberEquityHousekeeperImage               @"会员权益_管家预约.png"

#define CMLConfirmAppointmentButtonSelectImg          @"会员中心_弹窗_确认预约_选中.png"
#define CMLConfirmAppointmentButtonNoSelectImg        @"会员中心_弹窗_确认预约_未选中.png"


#define InvitationImg                     @"邀请函背景.png"
#define InvitationUpImg                   @"activity_invitation_arrow.png"
#define InvitationQRImg                   @"activity_invitation_QR.png"
#define ShowDetailMessageImg              @"details_unfold.png"
#define ShowActivityMessageCostImg        @"费用.png"
#define CostActivityMessageImg            @"personal_booking_activity_details_charge_explain.png"

#define UpGradePigmentFirstprerogativeImg   @"名流盛宴.png"
#define UpGradePigmentSecondprerogativeImg  @"聚会交流.png"
#define UpGradePigmentThirdprerogativeImg   @"缤纷花伴.png"
#define UpGradePigmentFourthprerogativeImg  @"生活资讯.png"
#define UpGradePigmentFifthprerogativeImg   @"吃喝玩乐.png"
#define UpGradePigmentSixthprerogativeImg   @"福利特惠.png"
#define UpGradePigmentSeventhprerogativeImg @"定制服务.png"
#define UpGradePigmentEighthprerogativeImg  @"名品资讯.png"

#define UpGradeGoldFirstprerogativeImg      @"名流盛宴VIP.png"
#define UpGradeGoldSecondprerogativeImg     @"时尚社交.png"
#define UpGradeGoldThirdprerogativeImg      @"花伴女王.png"
#define UpGradeGoldFourthprerogativeImg     @"私享福利.png"
#define UpGradeGoldFifthprerogativeImg      @"消费管家.png"
#define UpGradeGoldSixthprerogativeImg      @"畅游世界.png"
#define UpGradeGoldSeventhprerogativeImg    @"私人定制.png"
#define UpGradeGoldEighthprerogativeImg     @"名品直采.png"

#define PrivateLetterOppositeImg          @"私信对话框_对方_点击_ios.png"
#define PrivateLetterOwnImg               @"私信对话框_我_点击_ios.png"

#define PrefectureMoreMessageImg          @"专区_查看更多.png"
#define PreffectureDecorateImg            @"专区_标题装饰.png"
#define PrefectureHitNumImg               @"专区_浏览量.png"
#define PrefectureInfoBackImg             @"专区_拍品详情_返回"
#define PrefectureInfoShareImg            @"专区_拍品详情_分享"
#define InformationBottomImg              @"专区_单品详情遮照.png"
#define PrefectureImg                     @"视频播放.png"
#define AddressDefaultImg                 @"默认地址_选择框.png"
#define AddressSelectedImg                @"默认地址_选中.png"
#define GoodsScrollBackImg                @"单品_返回.png"
#define GoodsScrollShareImg               @"单品_分享.png"
#define GoodsBackImg                      @"单品_返回.png"
#define GoodsShareImg                     @"单品_分享.png"
#define GoodsCustomerServiceImg           @"单品_客服.png"
#define GoodsCustomerServiceScrollImg     @"单品_客服.png"
#define GoodsNumAddImg                    @"单品_数量_加.png"
#define GoodsNumReduceImg                 @"单品_数量_减.png"
#define GoodsWXPayImg                     @"支付_微信.png"
#define GoodsZFBPayImg                    @"支付_支付宝.png"
#define GoodsSelectImg                    @"单品_支付_选择.png"
#define GoodsSelectedImg                  @"单品_支付_选中.png"
#define GoodsPaySuccessImg                @"单品_支付完成.png"
#define NoUserAddressImg                  @"我的_我的资料_我的收货信息_无地址.png"
#define GoodsCloseImg                     @"goodsCloseBtn.png"
#define GoodsAttributeViewNumAddImg       @"加号.png"
#define GoodsAttributeViewNumReduceImg    @"减号.png"
#define NewDetailMessageBackImg           @"返回.png"
#define NewDetailMessageFavImg            @"收藏.png"
#define NewDEtailMessageFavedImg          @"已收藏.png"
#define NewDetailMessageShareImg          @"分享.png"
#define NewDetailMessageBlackBackImg      @"转换_返回.png"
#define NewDetailMessageBlackFavImg       @"转换_收藏.png"
#define NewDetailMessageBlackFavedImg     @"转换_已收藏.png"
#define NewDetailMessageBlackShareImg     @"转换_分享.png"
#define NewDetailMessageTeltNumBtnImg     @"电话.png"
#define NewDetailMessageAddressBtnImg     @"地点.png"
#define NewDEtailMessageBottomLogoImg     @"活动_底部logo.png"
#define IntegrationDetailMessageImg       @"我的积分_积分明细.png"
#define IntegrationExchangeImg            @"我的积分_我的兑换.png"
#define IntegrationTaskImg                @"我的积分_积分任务.png"
#define IntegrationBgImg                  @"我的积分_背景.png"
#define IntegrationEnterRulesImg          @"我的积分_积分规则_箭头.png"
#define IntegrationIconImg                @"积分币.png"
#define IntegrationTaskOfInvationImg      @"积分任务_邀请好友.png"
#define IntegrationTaskOfBuyGoodsImg      @"积分任务_购买商品.png"
#define IntegrationTaskOfSignInImg        @"积分任务_签到.png"
#define IntegrationTaskOfAppointmentServeImg @"积分任务_预订高端定制.png"
#define IntegrationTaskOfBookFreeActivityImg @"积分任务_预订免费活动.png"
#define IntegrationTaskOfBookCostActivityImg @"积分任务_预订收费活动.png"
#define IntegrationTaskOfUserMessageImg      @"积分任务_个人资料.png"
#define NoExchangeGoodsImg                   @"无兑换.png"
#define IntegraSignInSuccessImg              @"积分任务_签到成功.png"
#define NewUpGradeImg                        @"icon_user_privilege_up_bg.png"
#define InviteFriendsImg                     @"我的_邀请好友.png"
#define GreenInvitetionImg                   @"我的_邀请好友_进入.png"
#define InviteFriendsBgImg                   @"邀请好友_背景.png"
#define InviteFriendsDetailImg               @"邀请好友_1.png"

#define InviteWechat_momentShareImg          @"邀请好友_朋友圈.png"
#define InviteWechat_CShareImg               @"邀请好友_微信.png"
#define InviteQQShareImg                     @"邀请好友_qq.png"
#define InviteSinaShareImg                   @"邀请好友_微博.png"
#define SignIconImg                          @"签到_点击签到.png"
#define NewImg                               @"我的_new.png"
#define SignSuccessImg                       @"签到_签到成功.png"
#define LoadTopImg1                          @"登录注册_头图_1.png"
#define LoadTopImg2                          @"登录注册_头图_2.png"
#define LoadTopImg3                          @"登录注册_头图_3.png"
#define LoadTopImg4                          @"登录注册_头图_4.png"
#define NewPushTimeLineImg                   @"发布动态.png"
#define CMLLvlOneImg                         @"粉色会员.png"
#define CMLLvlTwoImg                         @"黛色会员.png"
#define CMLLvlThreeImg                        @"金色会员.png"
#define CMLLvlFourImg                         @"墨色会员.png"
#define PushProjectTopBgImg                   @"发布项目_默认封面.png"
#define PushProjectTopBtnImg                  @"发布项目_上传封面.png"
#define AlterProjectTopBtnImg                 @"发布项目_修改封面.png"
#define UserTimelIneLikeBtnImg                @"信息流_赞_默认.png"
#define UserTimelIneLikedBtnImg               @"信息流_赞_点亮.png"
#define UserTimelIneCommentImg                @"信息流_评论.png"
#define ProjectTagImg                         @"花伴项目_标签.png"
#define XuXianImg                             @"发布项目_默认封面_虚线.png"
#define PersonalHomePageNoProjectImg          @"个人主页_项目_无.png"
#define DetailMessageCommentImg               @"详情_评论_标签栏.png"
#define DetailMessageLikeImg                  @"详情_赞_标签栏_默认.png"
#define DetailMessageLikedImg                 @"详情_赞_标签栏_点亮.png"
#define NewAttentionDefaultImg                @"关注.png"
#define NewAttentionedImg                     @"已关注.png"
#define GetCardBtnImg                         @"获取名片.png"
#define VIPHomePageLetterImg                  @"用户主页_私信.png"
#define NoProjectImg                          @"个人主页_项目_未发布.png"
#define NoAttentionUserImg                    @"花伴事迹_无关注.png"
#define NoticeZanImg                          @"我的消息_赞.png"
#define NoticeCommentImg                      @"我的消息_评论.png"
#define NoticeAttentionImg                    @"我的消息_关注.png"
#define NoticeSysMessageImg                   @"我的消息_系统消息.png"
#define NewMessagePromImg                     @"我的消息_新消息提示.png"
#define CommentLikedImg                       @"详情_评论_赞_点亮.png"
#define CommentLikeImg                        @"详情_评论_赞_默认.png"
#define NewTimeLineRecordIdImg                @"个人主页_事迹_未发布.png"
#define PostAttentionActivityImg              @"关联活动.png"
#define PostAttentionActivityEnterImg         @"关联活动_指示箭头.png"
#define ReportImg                             @"举报.png"
#define AddBlackListImg                       @"用户主页_拉黑举报.png"
#define MembetTopicImg                        @"话题.png"
#define MemberArticleImg                      @"文章.png"
#define PushUserMessageTopicImg               @"发布事迹_关联话题.png"
#define MainterfaceTopicEnterImg              @"首页_推荐_专题_数量指示.png"
#define MainterfaceImageEnterImg              @"首页_相册_数量指示.png"
#define TagGrowImg                            @"首页_推荐_商城推荐_分类标识_成长.png"
#define TagHealthyImg                         @"首页_推荐_商城推荐_分类标识_健康.png"
#define TagTravelImg                          @"首页_推荐_商城推荐_分类标识_旅游.png"
#define TagFashionImg                         @"首页_推荐_商城推荐_分类标识_时尚.png"
#define TagGrowMesImg                         @"服务_类别标签_信息流_成长.png"
#define TagHealthyMesImg                      @"服务_类别标签_信息流_健康.png"
#define TagTravelMesImg                       @"服务_类别标签_信息流_旅游.png"
#define TagFashionMesImg                      @"服务_类别标签_信息流_时尚.png"
#define BrandAllEnterImg                      @"商城_推荐_单品_查看全部_2.png"
#define BrandAllEnter2Img                     @"商城_推荐_单品_查看全部_1.png"
#define DownPromImg                           @"商城_品牌主页_下拉指示.png"
#define SBCarImg                              @"商城_购物车.png"
#define ServeProtctImg                        @"商品保障说明.png"
#define PushRecommendImg                      @"图片背景_商城_详情_我也要推荐.png"
#define RecommendAllImg                       @"图片背景_商城_详情_查看全部.png"
#define RecommendBgImg                        @"图片背景_商城_详情_推荐.png"
#define FristRecommendBgImg                   @"图片背景_商城_详情_发布第一条推荐.png"
#define FristRecommendpromImg                 @"推荐人_发布第一条推荐.png"
#define DeleteRecommendImg                    @"推荐人_我的推荐_删除.png"
#define DeletePromImg                         @"推荐人_我的推荐_删除提示.png"
#define BrandServeImg                         @"商品保障说明_详情.png"
#define MailCarAddBtnImg                      @"购物车_数量_加.png"
#define MailForbridAddBtnImg                  @"购物车_数量_限量不可加.png"
#define MailCarReduceBtnImg                   @"购物车_数量_减.png"
#define MailCarBrandNoSelectImg               @"购物车_默认未选中.png"
#define MailCarBrandSelectedImg               @"购物车_选中.png"
#define MailCarBrandForbridSelectImg          @"购物车_失效.png"
#define MailAfterSalesSelectedImg             @"售后_选中类型.png"
#define MailAfterSalesNormalImg               @"售后_未选中.png"
#define MailShoppingCarNoBrandImg             @"购物车_无商品.png"
#define MailShaDowImg                         @"图片背景_标题价格_底部阴影.png"
#define NewMesListVideoPlayImg                @"信息流_视频播放.png"

#define HomePageCalendarBubbleImg             @"首页_日历.png"
#define HomePageStoreBubbleImg                @"商城.png"
#define HomePageImagesBubbleImg               @"首页_图集.png"
#define ServeDetailCustomerserveBubbleImg     @"商城_客服.png"
#define ServeDetailBuyBubbleImg               @"商城_立即购买.png"

#define XHomePageCalendarBubbleImg             @"X_首页_日历.png"
#define XHomePageStoreBubbleImg                @"X_商城.png"
#define XHomePageImagesBubbleImg               @"X_首页_图集.png"
#define XServeDetailCustomerserveBubbleImg     @"X_商城_客服.png"
#define XServeDetailBuyBubbleImg               @"X_商城_立即购买.png"

#define TopicTagImg                            @"biaoqianzi.png"
#define TableListImageEncryptImg               @"icon_mima.png"
#define ChildImageEncryptImg                   @"icon_xuanfukuang.png"
#define RecommendUserVideoImg                  @"icon_yinpin.png"

#define PriceVerbDefaultImg                     @"箭头 三种状态 01.png"
#define PriceVerbUpImg                          @"箭头 三种状态 02.png"
#define PriceVerbDownImg                        @"箭头 三种状态 03.png"

#define ServeDepositImg                         @"订金.png"
#define ServeFullAmountImg                      @"全款.png"
#define ProductDetailImg                        @"产品详情.png"
#define BrandStoryImg                           @"品牌故事.png"
#define ProductPriceImg                         @"产品价格.png"

#define ListActivityTimeImg                     @"列表时间.png"
#define ListActivityAddressImg                  @"列表地点.png"
#define WorldFashionMapImg                      @"全球时尚_地图_修.png"
#define ListActivityTagImg                      @"列表活动tag.png"
#define ListArcticleTagImg                      @"列表资讯tag.png"

#define VersionPromImg                          @"版本提示.png"
#define ArticleBottomLogoImg                    @"articleBottomLogo.png"
#define ArticleTimeImg                          @"6小时前.png"

#define LogohorizontalImg                       @"logo_h.png"

/*浏览量*/
#define CMLHitImage                             @"浏览.png"
#define CMLOpenPushHintImage                    @"推送开启提示.png"

/*优惠券-我的卡券*/
#define CMLDiscountCouponUseRuleUp              @"我的卡券_使用规则_上.png"
#define CMLDiscountCouponUseRuleDown            @"我的卡券_使用规则_下.png"
#define CMLDiscountCouponOverdue                @"我的卡券_已过期.png"/*已过期图标*/
#define CMLDiscountCouponBeenUsed               @"我的卡券_已使用.png"
/*我的卡券-优惠券*/
#define CMLDiscountCouponNoSelectLine           @"我的卡券_优惠券_未选中_.png"/*虚线*/
#define CMLDiscountCouponNoSelectCase           @"我的卡券_优惠券_未选中.png" /*框*/
#define CMLDiscountCouponCaseDown               @"我的卡券_优惠券_下拉.png"  /*框*/
#define CMLDiscountCouponCaseDownNoSelect       @"我的卡券_优惠券_下拉_未选中.png"/*框*/
#define CMLDiscountCouponBigOverdue             @"我的卡券_优惠券_已过期.png"
#define CMLDiscountCouponBigBeenUsed            @"我的卡券_优惠券_已使用.png"
#define CMLDiscountCoupon                       @"我的卡券_优惠券.png"/*可使用优惠券背景框*/
#define CMLDiscountCouponSelectLine             @"直线.png"/*虚线*/
#define CMLDisconutCouponNotChoose              @"优惠券_未选中.png"
#define CMLDisconutCouponChoose                 @"优惠券_选中.png"

#define CMLEnterDiscountCouponIcon              @"进入icon.png"

#endif /* CommonImg_h */
